# -*- coding: utf-8 -*-
"""Facial emotion detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16qeKqIgrBa5Ig8qp5LMsTJUBFs15CzxO
"""

import zipfile
zip_ref = zipfile.ZipFile('/content/archive (3).zip', 'r')
zip_ref.extractall('/content')
zip_ref.close()

import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten

train_ds = keras.utils.image_dataset_from_directory(
    directory = ('/content/train'),
    labels="inferred",
    label_mode="int",
    class_names=included_classes,
    color_mode="rgb",
    batch_size=32,
    image_size=(48, 48),
    shuffle=True,
)

validation_ds = keras.utils.image_dataset_from_directory(
    directory = ('/content/test'),
    labels="inferred",
    label_mode="int",
    class_names=included_classes,
    color_mode="rgb",
    batch_size=32,
    image_size=(48, 48),
    shuffle=True,
)

#Normalization
def process(image, label):
  image = tf.cast(image/255, tf.float32)
  return image, label

train_ds = train_ds.map(process)
validation_ds = validation_ds.map(process)

from tensorflow.keras import layers

data_augmentation = tf.keras.Sequential([
  layers.RandomFlip("horizontal"),
  layers.RandomRotation(0.02),
  layers.RandomZoom(0.2),
  layers.RandomContrast(0.2)
])

from tensorflow.keras.layers import Dropout
from keras.layers import BatchNormalization

model = Sequential()
model.add(data_augmentation)
model.add(Conv2D(32, kernel_size = (3,3), padding = 'same', activation = 'relu', input_shape = (48,48,3)))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size = (2,2), strides = 2, padding = 'same'))


model.add(Conv2D(64, kernel_size = (3,3), padding = 'valid', activation = 'relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2), strides = 2, padding = 'same'))

model.add(Conv2D(128, kernel_size = (3,3), padding = 'valid', activation = 'relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2), strides = 2, padding = 'same'))

model.add(Conv2D(256, kernel_size = (3,3), padding = 'valid', activation = 'relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2), strides = 2, padding = 'same'))


model.add(Flatten())

model.add(Dense(512, activation = 'relu'))
model.add(Dropout(0.3))

model.add(Dense(128, activation = 'relu'))
model.add(Dropout(0.2))

model.add(Dense(64, activation = 'relu'))
model.add(Dropout(0.1))

model.add(Dense(5, activation = 'softmax'))

model.build()

model.summary()

from keras.callbacks import EarlyStopping

early_stop = keras.callbacks.EarlyStopping(
    monitor="val_loss",
    min_delta=0,
    patience=5,
    verbose=0,
)

model.compile(optimizer = 'adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(
                  from_logits=True), metrics = ['accuracy'])

history = model.fit(train_ds, epochs = 100, validation_data = validation_ds, callbacks = [early_stop] )

model.evaluate(validation_ds)

import matplotlib.pyplot as plt
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(loc='upper left')
plt.show()

